admins:  # Administrators who cannot be banned (all in lowercase)
  - tynaevbe
  - taskov1ch

messages:  # Section with messages for different scenarios.
  for_banned:  # Messages sent to banned players.
    screen: |-  # Kick screen
      You have been banned by player {%by}.
      Reason: {%reason}.

  for_sender:  # Messages for the player using the ban command.
    ban_command:
      usage: "Usage: /bban <player> <reason>"  # Instructions for using the ban command.
      is_op: "The person you are trying to ban is an ADMINISTRATOR!"  # Error if a player tries to ban an admin.
      long_reason: "The reason for the ban is too long."  # The message if the reason crosses the length of 200 characters.

      # If the ban was from the administration, then the posts will not be created,
      # and they themselves will not need to provide evidence.
      success: |-  # Message on successful player ban.
        You have banned player {%banned} for the reason: {%reason}.
        You must provide evidence in the VKontakte community or Telegram channel, otherwise, your account will be banned!
        You have 6 hours to provide evidence.

    # WARNING! When you unban, posts from VK or TG will not be deleted!
    # Not because it's difficult, but just because of my laziness )
    # I will definitely fix it in the future.
    unban_command:
      usage: "Usage: /bban <player> <reason>"  # Instructions for using the unban command.
      not_banned: "This player is not banned."  # A message when trying to unban a non-banned player.
      success: "The player has been successfully unbanned."  # # Message on successful player unban.

    abuse: |-  # Message for abuse of the ban command.
      You have been permanently banned for abusing the ban command.

    awarded: |- # A message for the hero (And I'm still waiting for a hero...)
      You have successfully banned the violator and presented evidence, you have been given a reward!

databases:  # Database settings.
  type: mysql  # Type of database. Here it's only MySQL.
  mysql:
    host: "127.0.0.1:3306"  # Host and port for the MySQL database.
    username: root  # Username for the database connection.
    password: qwerty  # Password for the database connection.
    schema: banedetta  # Name of the database schema (table set).

  worker-limit: 2  # Limit of workers that can simultaneously process tasks.

# Enter a list of commands that will be executed on behalf of the console.
# If anything, this is a reward for the players who actually banned the violator and presented evidence.
rewards:
  - kick {%player} LOL :)

time_limit: 6  # Time to provide evidence in hours (if there is no evidence, then ban)