# Какой метод банов пердпочитаете? ("nick", "xid")
ban_method: nick

vk:
  # Да простят меня боги программирования за то что храню такую инфу в конфиге
  # Ключ доступа пользователя, полученным в Standalone-приложении через Implicit Flow
  token: "vk1.a.dci74ySBJv87dyCETKTnfCL2vrdcWrfjsG7TAdezhs6hJu_ZQMjv8KipWi69djL7R6MWUG5Ma_6WcYkbPpzdjodZf0D1VIgvFQng5RQtBP8sKgblspAxb-YJ3kc3oVEF4ngMdw9G7XOdoALBrRHVai0euQPdKMiYOgM0K3-Nlg3_gPsGquG2r2OE6m1_Pn7TkecdLEAV-S1n2czH7z1ukQ"

  # ID сообщества (без минуса)
  group_id: 224130500

  # Список тех, что может подверждать или отклонять
  admins:
    - 614763437

  posts:
    waiting:
      attachment: "photo-224130500_457239036"
      message: |-
        Игрок {nickname} был заблокирован игроком {by}
        Причина: {reason}.
        Ожидается доказательства в течение 6 часов, в ином случае ваш аккаунт будет заблокирован.

    confirmed:
      attachment: "photo-224130500_457239042"
      message: |-
        Игрок {nickname} был заблокирован игроком {by}
        Причина: {reason}.
        Подверждено!

    denied:
      attachment: "photo-224130500_457239037"
      message: |-
        Игрок {nickname} был заблокирован игроком {by}
        Причина: {reason}.
        Не подверждено! Игрок был разблокирован.

databases:
  # Тип базы данных. Поддерживаются "sqlite" и "mysql".
  type: sqlite

  # Изменяйте эти настройки только в случае выбора "sqlite".
  sqlite:

    # Имя файла базы данных в папке данных плагина.
    # Вы также можете указать абсолютный путь.
    file: database.db

  # Изменяйте эти настройки только в случае выбора "mysql".
  mysql:
    host: "127.0.0.1:3306"

    # Избегайте использования пользователя "root" по соображениям безопасности.
    username: root
    password: qwerty
    schema: banedetta

  # Максимальное количество одновременных SQL-запросов
  # Рекомендуется: 1 для sqlite, 2 для MySQL. Вы можете дополнительно увеличить это значение, если ваше соединение MySQL очень медленное.
  worker-limit: 1
