# Administrators who cannot be banned
admins:
  - tynaevbe
  - taskov1ch

messages:  # Section with messages for different scenarios.
  for_banned:  # Messages sent to banned players.
    screen: |-  # Kick screen
      You have been banned by player {%by}.
      Reason: {%reason}.

  for_sender:  # Messages for the player using the ban command.
    command:
      help: "Usage: /bban <player> <reason>"  # Instructions for using the ban command.
      is_op: "The person you are trying to ban is an ADMINISTRATOR!"  # Error if a player tries to ban an admin.
      success: |-  # Message on successful player ban.
        You have banned player {%banned} for the reason: {%reason}.
        You must provide evidence in the VKontakte community or Telegram channel, otherwise, your account will be banned!
        You have 6 hours to provide evidence.

    abuse: |-  # Message for abuse of the ban command.
      You have been permanently banned for abusing the ban command.

    awarded: |- # A message for the hero (And I'm still waiting for a hero...)
      You have successfully banned the violator and presented evidence, you have been given a reward!

databases:  # Database settings.
  type: mysql  # Type of database. Here it's only MySQL.
  mysql:
    host: "127.0.0.1:3306"  # Host and port for the MySQL database.
    username: root  # Username for the database connection.
    password: qwerty  # Password for the database connection.
    schema: banedetta  # Name of the database schema (table set).

  worker-limit: 2  # Limit of workers that can simultaneously process tasks.

# Enter a list of commands that will be executed on behalf of the console.
# If anything, this is a reward for the players who actually banned the violator and presented evidence.
rewards:
  - kick {%player} LOL :)