posts:
  waiting: |-
    Игрок {banned} был заблокирован игроком {by}
    Причина: {reason}.
    Ожидается доказательства в течение 6 часов, в ином случае ваш аккаунт будет заблокирован.

  confirmed: |-
    Игрок {banned} был заблокирован игроком {by}
    Причина: {reason}.
    Подтверждено!

  denied: |-
    Игрок {banned} был заблокирован игроком {by}
    Причина: {reason}.
    Не подтверждено! {banned} был разблокирован, а {by} заблокирован.

  abuse: |-
    Вы были навсегда заблокированы за злоупотребление командой блокировки.

messages:
  for_banned:
    waiting: |-
      Вы были заблокированы игроком {by}.
      Причина: {reason}.
      На данный момент ваш бан временный, и ожидается подтверждения модераторов.

    confirmed: |-
      Вы были заблокированы игроком {by}.
      Причина: {reason}.
      Ваша блокировка была подверждена модераторами, увы.
      Аккаунт заблокирован навсегда (

  for_sender:
    command:
      help: "Использование: /bban <игрок> <причина>"
      is_op: "Тот кого бы пытаесь забанить, оператор сервера!"
      success: |-
        Вы заблокировали игрока {banned} по причине: {reason}
        Вам необходимо предоставить доказательства в сообществе ВК, в ином случае вам аккаунт будет заблокирован.
    abuse: |-
      Вы были навсегда заблокированы за злоупотребление командой блокировки.

databases:
  # Тип базы данных. Поддерживаются "sqlite" и "mysql".
  type: sqlite

  # Изменяйте эти настройки только в случае выбора "sqlite".
  sqlite:
    # Имя файла базы данных в папке данных плагина.
    # Вы также можете указать абсолютный путь.
    file: database.db

  # Изменяйте эти настройки только в случае выбора "mysql".
  mysql:
    host: "127.0.0.1:3306"

    # Избегайте использования пользователя "root" по соображениям безопасности.
    username: root
    password: qwerty
    schema: banedetta

  # Максимальное количество одновременных SQL-запросов
  # Рекомендуется: 1 для sqlite, 2 для MySQL. Вы можете дополнительно увеличить это значение, если ваше соединение MySQL очень медленное.
  worker-limit: 1
